import { readFileSync } from "node:fs";
import "fake-indexeddb/auto";
import { JSDOM } from "jsdom";
const dom=new JSDOM('<!doctype html><body><div id="root"></div></body>',{url:"http://localhost/monitor/",pretendToBeVisual:true});
globalThis.window=dom.window; globalThis.document=dom.window.document;
for(const k of ["navigator","HTMLElement","Element","Node","SVGElement","getComputedStyle","requestAnimationFrame","cancelAnimationFrame","CustomEvent","Event","localStorage","MutationObserver","location","history"])
  if(!(k in globalThis)) globalThis[k]=dom.window[k];
globalThis.matchMedia=()=>({matches:false,addListener(){},removeListener(){},addEventListener(){},removeEventListener(){}});
globalThis.fetch=async()=>({ok:false,status:0,json:async()=>({})});
const raw=JSON.parse(readFileSync("/mnt/user-data/uploads/sleep-2026-08-30__1_.json","utf8"));
await new Promise((res,rej)=>{const r=indexedDB.open("baby-tracker",1);
 r.onupgradeneeded=()=>r.result.createObjectStore("kv");
 r.onsuccess=()=>{const t=r.result.transaction("kv","readwrite");
  t.objectStore("kv").put({profile:raw.profile,events:raw.events,auth:{token:"t",householdId:"h"},rev:0,bias:0,schema:2,profileDirty:false},"state");
  t.oncomplete=res;t.onerror=rej;};r.onerror=rej;});
const React=(await import("react")).default;
const {createRoot}=await import("react-dom/client");
const {default:App}=await import("./appbuild.mjs");
createRoot(document.getElementById("root")).render(React.createElement(App));
await new Promise(r=>setTimeout(r,900));
const click=(t)=>{const b=[...document.querySelectorAll("button")].find(x=>x.textContent.trim().startsWith(t));if(b)b.click();};
click("Неделя");
await new Promise(r=>setTimeout(r,300));
const rows = [...document.querySelectorAll(".week-row")];
console.log("строк недели:", rows.length);
rows.forEach((r,i)=>{
  const lab = r.querySelector(".week-lab")?.textContent;
  const hasNow = !!r.querySelector(".rib-now");
  console.log(`  ${i}: ${lab} -> засечка "сейчас": ${hasNow}`);
});
